global:
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from timing out first.
  #
  # Must be strictly positive. The default is 500ms.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 10s
   # Maximum number of open connections to any one target. Metric queries will run concurrently on multiple connections,
  # as will concurrent scrapes.
  
  max_connections: 3
  # Maximum number of idle connections to any one target. Unless you use very long collection intervals, this should
  # always be the same as max_connections.
 
  max_idle_connections: 3
  # Maximum number of maximum amount of time a connection may be reused. Expired connections may be closed lazily before reuse.
  # If 0, connections are not closed due to a connection's age.
  max_connection_lifetime: 5m

 

# The target to monitor and the collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. vertica)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  # data_source_name: 'vertica://<username>:<userpwd>@<exporterhostip>:5433/<databasename>'
  data_source_name: 'vertica://dbadmin:@vertica_docker:5433/VMart' #github auto test configration
 

  # Collectors (referenced by name) to execute on the target.
  collectors: [example ,example1]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
collector_files: 
# - "*.collector.yml"
- "*.collector.yml"

Log: 
  retention_day:  15 # Any integer value which represents days .
  max_log_filesize:  500 # Any integer value which represents log file size in  megabytes 


