name: Go

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Format
      run: make format
    - name: Test
      run: make test
    - name: Build
      run: make build

    - name: Set up a Vertica server
      timeout-minutes: 15
      run: |
          docker network create -d bridge vertica
          docker pull vertica/vertica-ce:12.0.0-0
          docker run -d -p 5433:5433 -p 5444:5444 \
            -itd --network=vertica \
            --name vertica_docker \
            vertica/vertica-ce
          echo "Vertica startup ..."
          until docker exec vertica_docker test -f /data/vertica/VMart/agent_start.out; do \
            echo "..."; \
            sleep 3; \
          done;
          echo "Vertica is up"

    - name: Set up a vertica-prometheus-exporter
      timeout-minutes: 15
      run: |
          docker build . -t vertica-prometheus-exporter
          docker run -d -i -p 9968:9968 -itd --network=vertica  --name vertica-prometheus-exporter vertica-prometheus-exporter:latest
          docker logs vertica-prometheus-exporter 
          echo "Vertica exporter started successfully..."
          docker ps
    - name: curl data using exporter from vertica database
      timeout-minutes: 15
      run: |
          echo "getting data using vertica-prometheus-exporter from vertica database..."
          curl --location --request GET 'http://localhost:9968/metrics'
          
      